<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Analisis.py" />
    <Compile Include="check_modelo.py" />
    <Compile Include="01_eda_analisis.py" />
  </ItemGroup>

</Project>
